/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RouteCustomizer.java
 *
 * Created on 1.6.2010, 21:34:38
 */
package php.agavi.ui.xmlpalette.items;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.KeyStroke;
import javax.swing.text.JTextComponent;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;

/**
 *
 * @author mle
 */
public class RouteCustomizer extends javax.swing.JPanel {

    private Dialog dialog = null;
    private DialogDescriptor descriptor = null;
    private boolean dialogOK = false;
    Route item;
    JTextComponent target;

    /** Creates new form RouteCustomizer */
    public RouteCustomizer(Route item, JTextComponent target) {
        this.item = item;
        this.target = target;

        initComponents();

        patch(callbacks);
        patch(defaults);
        patch(ignores);

    }

    /**
     * Patch the behaviour of a component.
     * TAB transfers focus to the next focusable component,
     * SHIFT+TAB transfers focus to the previous focusable component.
     *
     * @author kaimu
     * @param c	The component to be patched.
     */
    public static void patch(Component c) {
        Set<KeyStroke> strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("pressed TAB")));
        c.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, strokes);
        strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("shift pressed TAB")));
        c.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, strokes);
    }

    public boolean showDialog() {

        dialogOK = false;

        String displayName = "";
        try {
            displayName = NbBundle.getBundle("fi.necora.netbeans.xmlpalette.items.resources.Bundle").getString("NAME_html-ITEM"); // NOI18N
        } catch (Exception e) {
        }

        descriptor = new DialogDescriptor(this, NbBundle.getMessage(RouteCustomizer.class, "LBL_Customizer_InsertPrefix") + " " + displayName, true,
                DialogDescriptor.OK_CANCEL_OPTION, DialogDescriptor.OK_OPTION,
                new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        if (descriptor.getValue().equals(DialogDescriptor.OK_OPTION)) {
                            evaluateInput();
                            dialogOK = true;
                        }
                        dialog.dispose();
                    }
                });

        dialog = DialogDisplayer.getDefault().createDialog(descriptor);
        dialog.setVisible(true);
        repaint();

        return dialogOK;

    }

    private void evaluateInput() {

        item.setRouteName(routeName.getText());
        item.setRoutePattern(routePattern.getText());
        item.setCallbacks(callbacks.getText());
        item.setModule(module.getText());
        item.setAction(module.getText());
        item.setLocale(locale.getText());
        item.setSource(source.getText());
        item.setCut(cut.isSelected());
        item.setStop(stop.isSelected());
        item.setImply(imply.isSelected());
        item.setIgnores(ignores.getText());
        item.setDefaults(defaults.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    routeName = new javax.swing.JTextField();
    routePattern = new javax.swing.JTextField();
    module = new javax.swing.JTextField();
    action = new javax.swing.JTextField();
    output_type = new javax.swing.JTextField();
    source = new javax.swing.JTextField();
    locale = new javax.swing.JTextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    callbacks = new javax.swing.JTextArea();
    cut = new javax.swing.JCheckBox();
    stop = new javax.swing.JCheckBox();
    imply = new javax.swing.JCheckBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    ignores = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    defaults = new javax.swing.JTextArea();

    jLabel1.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel1.text")); // NOI18N

    jLabel2.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel2.text")); // NOI18N

    jLabel3.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel3.text")); // NOI18N

    jLabel4.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel4.text")); // NOI18N

    jLabel5.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel5.text")); // NOI18N

    jLabel6.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel6.text")); // NOI18N

    jLabel7.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel7.text")); // NOI18N

    jLabel8.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel8.text")); // NOI18N

    jLabel9.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel9.text")); // NOI18N

    jLabel10.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.jLabel10.text")); // NOI18N

    routeName.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.routeName.text")); // NOI18N

    routePattern.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.routePattern.text")); // NOI18N

    module.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.module.text")); // NOI18N

    action.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.action.text")); // NOI18N

    output_type.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.output_type.text")); // NOI18N

    source.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.source.text")); // NOI18N

    locale.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.locale.text")); // NOI18N

    callbacks.setColumns(20);
    callbacks.setRows(5);
    jScrollPane3.setViewportView(callbacks);

    cut.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.cut.text")); // NOI18N
    cut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cutActionPerformed(evt);
      }
    });

    stop.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.stop.text")); // NOI18N

    imply.setText(org.openide.util.NbBundle.getMessage(RouteCustomizer.class, "RouteCustomizer.imply.text")); // NOI18N

    ignores.setColumns(20);
    ignores.setRows(5);
    jScrollPane1.setViewportView(ignores);

    defaults.setColumns(20);
    defaults.setRows(5);
    jScrollPane2.setViewportView(defaults);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(routeName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(routePattern, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(module, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(action, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(output_type, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(source, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                  .addComponent(locale, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel5)
                  .addComponent(jLabel6)
                  .addComponent(jLabel7)
                  .addComponent(jLabel8)
                  .addComponent(jLabel2)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4)
                  .addComponent(jLabel1)
                  .addComponent(jLabel9))
                .addGap(171, 171, 171)))
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(89, 89, 89)
            .addComponent(cut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(imply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(96, 96, 96))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel10)
            .addContainerGap(171, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(routeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(8, 8, 8)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(routePattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(output_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(locale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(imply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField action;
  private javax.swing.JTextArea callbacks;
  private javax.swing.JCheckBox cut;
  private javax.swing.JTextArea defaults;
  private javax.swing.JTextArea ignores;
  private javax.swing.JCheckBox imply;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextField locale;
  private javax.swing.JTextField module;
  private javax.swing.JTextField output_type;
  private javax.swing.JTextField routeName;
  private javax.swing.JTextField routePattern;
  private javax.swing.JTextField source;
  private javax.swing.JCheckBox stop;
  // End of variables declaration//GEN-END:variables
}
