/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgaviCustomiserPanel.java
 *
 * Created on 8.11.2010, 15:31:28
 */

package php.agavi.ui.customiser;

import javax.rmi.CORBA.Util;
import org.netbeans.api.project.SourceGroup;
import org.netbeans.modules.php.api.phpmodule.PhpModule;
import org.netbeans.modules.php.project.PhpProject;
import org.netbeans.modules.php.project.PhpVisibilityQuery;
import org.netbeans.modules.php.project.ui.BrowseFolders;
import org.netbeans.modules.php.project.ui.Utils;
import org.openide.loaders.DataFolder;


/**
 *
 * @author mle
 */
public class AgaviCustomiserPanel extends javax.swing.JPanel {
    private final PhpModule phpModule;

    /** Creates new form AgaviCustomiserPanel */
    public AgaviCustomiserPanel(String sourceLocation, PhpModule phpModule) {
        initComponents();
        this.phpModule = phpModule;
        jLabel2.setText(sourceLocation);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(AgaviCustomiserPanel.class, "AgaviCustomiserPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(AgaviCustomiserPanel.class, "AgaviCustomiserPanel.jLabel2.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(AgaviCustomiserPanel.class, "AgaviCustomiserPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(385, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PhpProject phpProject = org.netbeans.modules.php.project.util.PhpProjectUtils.getPhpProject(this.phpModule.getSourceDirectory());
        String browseSourceFolder = Utils.browseSourceFolder(phpProject, "");
        jLabel2.setText(browseSourceFolder);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public String getSourcesDir() {
        return jLabel2.getText();
    }

}
